source 'https://rubygems.org'
ruby '2.1.3'

gem 'json'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-websocket'
gem 'sinatra-cross_origin'
gem 'houston'
gem 'gcm'
gem 'mongoid'
gem 'mongoid-enum'
gem 'resque'
gem 'bcrypt'
gem 'nexmo'
