source 'https://rubygems.org'
ruby '2.0.0'

gem 'json'
gem 'sinatra'
gem 'sinatra-websocket'
gem 'sinatra-cross_origin'
gem 'houston'
gem 'mongoid'
gem 'mongoid-enum'
gem 'rack-test'
gem 'rspec'
gem 'rqrcode_png'
gem 'resque'
